# This is a basic workflow to help you get started with Actions
name: rt-thread club automatic check-in

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # runs at 00:00 UTC every day
  schedule:
    - cron:  '0 0 * * *'
    - cron:  '0 12 * * *'
  push:
    branches: [ master ]
    paths-ignore:
      - docs/**
      - cmake/**
      - scripts/**
  pull_request:
    branches: [ master ]
    paths-ignore:
      - docs/**
      - cmake/**
      - scripts/**

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U selenium
        pip show selenium
    - name: Sign In
      env:
        CLUB_USERNAME: ${{ secrets.USERNAME }}
        CLUB_PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python rt_thread_club.py
        echo "CLUB_DAY_NUMBERS=$(cat sign_in_days.txt)" >> $GITHUB_ENV
    - name: 'Get Date'
      run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
    - name: Send email
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.yeah.net
        server_port: 25
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 签到小助手提醒您 (${{env.REPORT_DATE}})
        # 如果你想要发送纯文本邮件，请取消注释下一行，并注释掉 html_body 字段  
        # body: ${{ env.CLUB_DAY_NUMBERS }}  
        # 如果你想要发送 HTML 邮件，请确保 html_body 包含有效的 HTML 内容  
        html_body: "<html><body><p>签到小助手提醒您：${{ env.CLUB_DAY_NUMBERS }}</p></body></html>"
        to: ${{ secrets.EMAIL }}
        from: GitHub Actions
        attachments: /home/runner/paihang.png
