name: Update Repositories

on:
  schedule:
    - cron: '0 0 1 * *' # 每月 1 日触发
  push:
    branches:
      - master
    paths-ignore:
      - docs/**
      - cmake/**
      - scripts/**
  pull_request:
    branches:
      - master
    paths-ignore:
      - docs/**
      - cmake/**
      - scripts/**

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Set date
        run: echo "REPORT_DATE=$(date)" >> $GITHUB_ENV

      - name: Update timestamp
        run: echo "Last updated:$(date)" > timestamp.txt

      - name: Commit changes
        run: |
          git add timestamp.txt
          git commit -m "Update timestamp" || echo "No changes to commit"

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send email
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.yeah.net
          server_port: 25
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 签到小助手提醒您 (${{ env.REPORT_DATE }})
          html_body: |
            <html>
              <body>
                <h2>仓库更新通知</h2>
                <p>您好，以下是本次更新的详细内容：</p>
                <ul>
                  <li><strong>更新时间：</strong> ${{ env.REPORT_DATE }}</li>
                  <li><strong>更新的文件：</strong> timestamp.txt</li>
                  <li><strong>更新说明：</strong> 文件已成功更新以反映最新状态。</li>
                </ul>
                <p>如有任何疑问，请联系开发团队。</p>
                <p>此邮件由 GitHub Actions 自动生成，请勿回复。</p>
              </body>
            </html>
          to: ${{ secrets.EMAIL }}
          from: GitHub Actions

